name: Tencent Kubernetes Engine

on:
  push:
    branches: [ "main" ]

env:
  TKE_IMAGE_URL: ccr.ccs.tencentyun.com/demo/mywebapp
  TKE_REGION: ap-guangzhou
  TKE_CLUSTER_ID: cls-mywebapp
  DEPLOYMENT_NAME: tke-test

permissions:
  contents: read

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t ${TKE_IMAGE_URL}:${GITHUB_SHA} .

    - name: Login to TKE Registry
      run: |
        echo "${{ secrets.TKE_REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.TENCENT_CLOUD_ACCOUNT_ID }} --password-stdin ${TKE_IMAGE_URL}

    - name: Push image to TKE Registry
      run: |
        docker push ${TKE_IMAGE_URL}:${GITHUB_SHA}

    - name: Set up Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/

    - name: Set up TKE cluster credentials
      uses: TencentCloud/tke-cluster-credential-action@v1
      with:
        secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
        secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
        tke_region: ${{ env.TKE_REGION }}
        cluster_id: ${{ env.TKE_CLUSTER_ID }}

    - name: Set Kubernetes context
      run: |
        kubectl config use-context ${TKE_CLUSTER_ID}-context-default

    - name: Deploy to TKE
      run: |
        kustomize edit set image ${TKE_IMAGE_URL}:${GITHUB_SHA}
        kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/${DEPLOYMENT_NAME}

    - name: Display services
      run: |
        kubectl get services -o wide
